### ISSUE TITLE
Readme needs to specify maximum prefix charactors

### ISSUE THREAD

**Issue by rich-ehrhardt** [IBM/automation-aws-infra-openshift#30]
There is a limit of 15 characters for the naming of a ROSA cluster. The name can also only consist of alphanumeric characters and a dash. Given that the terraform code adds, `-cluster` to the end of the prefix, it limits the prefix to no more than 6 characters.

Either update the readme to specify this limit, or (better still) include an input validation on the prefix.

**Comment by indirakalagara** [comment]
Done
