### ISSUE TITLE
Apply-all.sh script not included in setup workspace script

### ISSUE THREAD

**Issue by rich-ehrhardt** [IBM/automation-aws-infra-openshift#46]
The `apply-all.sh` script should be copied to the workspace directory by the setup workspace script, but it is not. Only the `apply.sh` script is copied.

**Comment by indirakalagara** [comment]
Discussed with @rich-ehrhardt  and the scripts are in-line with IBM cloud infra automation. No script changes required.  Updated all ReadMe instructions to replace apply-all.sh references with apply.sh
