### ISSUE TITLE
Should merge the AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID into the script

### ISSUE THREAD

**Issue by rich-ehrhardt** [IBM/automation-aws-infra-openshift#51]
The AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID are specified in the credentials.template file as duplicates of the `TF_VAR_*` equivalents. They are used for the aws cli login credentials. Having to duplicate entries in the credentials file is not a good customer experience, we should merge these into the scripts which use the `aws` cli by passing the TF_VAR variables to those scripts and setting the environment variables only for those scripts.

**Comment by indirakalagara** [comment]
Updated launch script to append  the environment AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID  variables to the ENV_VARS based on the TF_Var equivalents.
